package br.ufes.inf.nemo.transparencia.domain;

// Generated 01/05/2015 21:48:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import br.ufes.inf.nemo.util.ejb3.persistence.PersistentObjectSupport;

/**
 * Elementodespesa generated by hbm2java
 */
@Entity
@Table(name = "elementodespesa", catalog = "transparencia")
public class ElementoDespesa extends PersistentObjectSupport implements Comparable<ElementoDespesa> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "cod_ElementoDespesa", unique = true, nullable = false)
	private int codElementoDespesa;
	
	@Column(name = "str_ElementoDespesa", length = 100)
	private String strElementoDespesa;
	
	@Column(name = "str_DescricaoElementoDespesa", length = 2500)
	private String strDescricaoElementoDespesa;	
	
	public int getCodElementoDespesa() {
		return this.codElementoDespesa;
	}

	public void setCodElementoDespesa(int codElementoDespesa) {
		this.codElementoDespesa = codElementoDespesa;
	}
	
	public String getStrElementoDespesa() {
		return this.strElementoDespesa;
	}

	public void setStrElementoDespesa(String strElementoDespesa) {
		this.strElementoDespesa = strElementoDespesa;
	}

	public String getStrDescricaoElementoDespesa() {
		return this.strDescricaoElementoDespesa;
	}

	public void setStrDescricaoElementoDespesa(
			String strDescricaoElementoDespesa) {
		this.strDescricaoElementoDespesa = strDescricaoElementoDespesa;
	}

	@Override
	public int compareTo(ElementoDespesa arg0) {
		// TODO Auto-generated method stub
		return 0;
	}	
}
