 package br.ufes.inf.nemo.transparencia.domain;

// Generated 01/05/2015 21:22:06 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import br.ufes.inf.nemo.util.ejb3.persistence.PersistentObjectSupport;

/**
 * Orgao generated by hbm2java
 */
@Entity
@Table(name = "orgao", catalog = "transparencia")
public class Orgao extends PersistentObjectSupport implements Comparable<Orgao> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Column(name = "str_NomeOrgao", length = 250)
	private String strNomeOrgao;	

	@Column(name = "cod_TipoPoder")
	private Integer codTipoPoder;
	
	@Column(name = "str_Sigla", length = 20)
	private String strSigla;

	public String getStrNomeOrgao() {
		return this.strNomeOrgao;
	}

	public void setStrNomeOrgao(String strNomeOrgao) {
		this.strNomeOrgao = strNomeOrgao;
	}

	public Integer getCodTipoPoder() {
		return this.codTipoPoder;
	}

	public void setCodTipoPoder(Integer codTipoPoder) {
		this.codTipoPoder = codTipoPoder;
	}

	public String getStrSigla() {
		return this.strSigla;
	}

	public void setStrSigla(String strSigla) {
		this.strSigla = strSigla;
	}
	

	@Override
	public int compareTo(Orgao o) {
		
		int cmp = codTipoPoder.compareTo(o.codTipoPoder);
		
		if (codTipoPoder == null) return 1;
		if (o.codTipoPoder == null) return -1;
		if (cmp != 0) return cmp;

		return uuid.compareTo(o.uuid);
	}
}
