package br.ufes.inf.nemo.transparencia.domain;

// Generated 01/05/2015 21:48:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import br.ufes.inf.nemo.util.ejb3.persistence.PersistentObjectSupport;

/**
 * Subelementodespesa generated by hbm2java
 */
@Entity
@Table(name = "subelementodespesa", catalog = "transparencia")
public class SubElementoDespesa  extends PersistentObjectSupport implements Comparable<SubElementoDespesa> {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/*
	@Column(name = "cod_SubelementoDespesa", unique = true, nullable = false)
	private int codSubelementoDespesa;
	*/

	@Column(name = "str_SubelementoDespesa", length = 250)
	private String strSubelementoDespesa;

	/*
	
	public int getCodSubelementoDespesa() {
		return this.codSubelementoDespesa;
	}

	public void setCodSubelementoDespesa(int codSubelementoDespesa) {
		this.codSubelementoDespesa = codSubelementoDespesa;
	}
	*/

	public String getStrSubelementoDespesa() {
		return this.strSubelementoDespesa;
	}

	public void setStrSubelementoDespesa(String strSubelementoDespesa) {
		this.strSubelementoDespesa = strSubelementoDespesa;
	}

	@Override
	public int compareTo(SubElementoDespesa o) {
		// TODO Auto-generated method stub
		return 0;
	}	
}
